version: "3.9"

services:
  app-pi:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./pain_information:/pain_information
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db-pi
    env_file:
      - ./.env
    networks:
      - pi-net

  db-pi:
    image: postgres:16-alpine
    volumes:
      - pi_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - pi-net

volumes:
  pi_postgres_data:

networks:
  pi-net:
