# Generated by Django 4.2.11 on 2024-03-22 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PainInformation',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('area', models.CharField(max_length=50)),
                ('detailed_area_place', models.CharField(max_length=50)),
                ('type_of_pain', models.CharField(choices=[('pulsating', 'Ból pulsujący'), ('dull', 'Ból tępy'), ('sharp', 'Ból ostry'), ('stabbing', 'Ból kłujący'), ('burning', 'Ból palący')], max_length=50)),
                ('intensity_of_pain', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('has_additional_info', models.BooleanField(default=False)),
                ('has_diagnosis', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.paininformation')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=3)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=3)),
                ('age', models.PositiveSmallIntegerField()),
                ('past_illnesses', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.paininformation')),
            ],
        ),
    ]
