# Generated by Django 4.2.11 on 2024-03-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='height_cm',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='past_illnesses',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='weight_kg',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='paininformation',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
