# Generated by Django 4.2.11 on 2024-03-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_additionalinfo_height_cm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='height_cm',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='weight_kg',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
