# Generated by Django 4.2.11 on 2024-03-25 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_additionalinfo_height_cm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='id',
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.paininformation'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.paininformation'),
        ),
    ]
