# Generated by Django 4.2.13 on 2024-06-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_paininformation_type_of_pain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paininformation',
            name='area',
        ),
        migrations.RemoveField(
            model_name='paininformation',
            name='detailed_area_place',
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='current_medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paininformation',
            name='pain_location_x',
            field=models.DecimalField(decimal_places=1, default=-500, max_digits=4),
        ),
        migrations.AddField(
            model_name='paininformation',
            name='pain_location_y',
            field=models.DecimalField(decimal_places=1, default=-500, max_digits=4),
        ),
        migrations.AlterField(
            model_name='paininformation',
            name='type_of_pain',
            field=models.CharField(choices=[('pulsating', 'Pulsating'), ('sharp', 'Sharp'), ('dull', 'Dull'), ('throbbing', 'Throbbing')], max_length=12),
        ),
    ]
