# Generated by Django 4.2.13 on 2024-06-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_paininformation_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paininformation',
            name='body_side',
            field=models.CharField(blank=True, choices=[('front', 'Front'), ('back', 'Back'), ('leftSide', 'Left Side'), ('rightSide', 'Right Side')], max_length=10),
        ),
    ]
